-- ============================================================
-- Seed: 005_seed_skills.sql
-- Description: Pre-loaded skill tag library (≥300 entries)
--              5 categories: programming | framework | tool |
--              soft_skill | language
--              Per PARALLEL_C2 T-C2-2 spec.
-- Safe to re-run: ON CONFLICT (name_zh) DO NOTHING
-- ============================================================

INSERT INTO seed_skills (name_zh, name_en, category, sort_order) VALUES

-- ══════════════════════════════════════════════════════════
-- CATEGORY: programming  (编程语言)  ~50 entries
-- ══════════════════════════════════════════════════════════
('Python',            'Python',             'programming',   1),
('JavaScript',        'JavaScript',         'programming',   2),
('TypeScript',        'TypeScript',         'programming',   3),
('Java',              'Java',               'programming',   4),
('C++',               'C++',                'programming',   5),
('C',                 'C',                  'programming',   6),
('C#',                'C#',                 'programming',   7),
('Go',                'Go (Golang)',         'programming',   8),
('Rust',              'Rust',               'programming',   9),
('Kotlin',            'Kotlin',             'programming',  10),
('Swift',             'Swift',              'programming',  11),
('Objective-C',       'Objective-C',        'programming',  12),
('Ruby',              'Ruby',               'programming',  13),
('PHP',               'PHP',                'programming',  14),
('Scala',             'Scala',              'programming',  15),
('R',                 'R',                  'programming',  16),
('MATLAB',            'MATLAB',             'programming',  17),
('Shell / Bash',      'Shell / Bash',       'programming',  18),
('PowerShell',        'PowerShell',         'programming',  19),
('Dart',              'Dart',               'programming',  20),
('Lua',               'Lua',                'programming',  21),
('Perl',              'Perl',               'programming',  22),
('Haskell',           'Haskell',            'programming',  23),
('Elixir',            'Elixir',             'programming',  24),
('Erlang',            'Erlang',             'programming',  25),
('Clojure',           'Clojure',            'programming',  26),
('F#',                'F#',                 'programming',  27),
('Groovy',            'Groovy',             'programming',  28),
('Julia',             'Julia',              'programming',  29),
('COBOL',             'COBOL',              'programming',  30),
('Fortran',           'Fortran',            'programming',  31),
('Assembly',          'Assembly',           'programming',  32),
('SQL',               'SQL',                'programming',  33),
('PL/SQL',            'PL/SQL',             'programming',  34),
('T-SQL',             'T-SQL',              'programming',  35),
('GraphQL',           'GraphQL',            'programming',  36),
('HTML',              'HTML',               'programming',  37),
('CSS',               'CSS',                'programming',  38),
('Sass / SCSS',       'Sass / SCSS',        'programming',  39),
('Solidity',          'Solidity',           'programming',  40),
('WebAssembly',       'WebAssembly',        'programming',  41),
('VBA',               'VBA',                'programming',  42),
('Apex (Salesforce)', 'Apex (Salesforce)',  'programming',  43),
('VHDL',              'VHDL',               'programming',  44),
('Verilog',           'Verilog',            'programming',  45),
('Prolog',            'Prolog',             'programming',  46),
('Scheme',            'Scheme',             'programming',  47),
('Tcl',               'Tcl',                'programming',  48),
('Nim',               'Nim',                'programming',  49),
('Zig',               'Zig',                'programming',  50),

-- ══════════════════════════════════════════════════════════
-- CATEGORY: framework  (框架与库)  ~90 entries
-- ══════════════════════════════════════════════════════════
('React',                   'React',                       'framework',   1),
('Next.js',                 'Next.js',                     'framework',   2),
('Vue.js',                  'Vue.js',                      'framework',   3),
('Nuxt.js',                 'Nuxt.js',                     'framework',   4),
('Angular',                 'Angular',                     'framework',   5),
('Svelte',                  'Svelte',                      'framework',   6),
('SvelteKit',               'SvelteKit',                   'framework',   7),
('Remix',                   'Remix',                       'framework',   8),
('Astro',                   'Astro',                       'framework',   9),
('Node.js',                 'Node.js',                     'framework',  10),
('Express.js',              'Express.js',                  'framework',  11),
('Fastify',                 'Fastify',                     'framework',  12),
('NestJS',                  'NestJS',                      'framework',  13),
('Koa',                     'Koa',                         'framework',  14),
('Hapi',                    'Hapi',                        'framework',  15),
('Django',                  'Django',                      'framework',  16),
('FastAPI',                 'FastAPI',                     'framework',  17),
('Flask',                   'Flask',                       'framework',  18),
('SQLAlchemy',              'SQLAlchemy',                  'framework',  19),
('Celery',                  'Celery',                      'framework',  20),
('Spring Boot',             'Spring Boot',                 'framework',  21),
('Spring MVC',              'Spring MVC',                  'framework',  22),
('MyBatis',                 'MyBatis',                     'framework',  23),
('Hibernate',               'Hibernate',                   'framework',  24),
('Micronaut',               'Micronaut',                   'framework',  25),
('Quarkus',                 'Quarkus',                     'framework',  26),
('ASP.NET Core',            'ASP.NET Core',                'framework',  27),
('Blazor',                  'Blazor',                      'framework',  28),
('Entity Framework',        'Entity Framework',            'framework',  29),
('Ruby on Rails',           'Ruby on Rails',               'framework',  30),
('Laravel',                 'Laravel',                     'framework',  31),
('Symfony',                 'Symfony',                     'framework',  32),
('Gin (Go)',                 'Gin (Go)',                     'framework',  33),
('Echo (Go)',                'Echo (Go)',                    'framework',  34),
('Fiber (Go)',               'Fiber (Go)',                   'framework',  35),
('gRPC',                    'gRPC',                        'framework',  36),
('GraphQL Apollo',          'Apollo GraphQL',              'framework',  37),
('tRPC',                    'tRPC',                        'framework',  38),
('TailwindCSS',             'Tailwind CSS',                'framework',  39),
('Bootstrap',               'Bootstrap',                   'framework',  40),
('Material UI',             'Material UI (MUI)',           'framework',  41),
('Ant Design',              'Ant Design',                  'framework',  42),
('shadcn/ui',               'shadcn/ui',                   'framework',  43),
('Radix UI',                'Radix UI',                    'framework',  44),
('Chakra UI',               'Chakra UI',                   'framework',  45),
('Redux',                   'Redux',                       'framework',  46),
('Zustand',                 'Zustand',                     'framework',  47),
('MobX',                    'MobX',                        'framework',  48),
('React Query / TanStack',  'TanStack Query',              'framework',  49),
('SWR',                     'SWR',                         'framework',  50),
('Recoil',                  'Recoil',                      'framework',  51),
('Jotai',                   'Jotai',                       'framework',  52),
('Pinia',                   'Pinia',                       'framework',  53),
('Vuex',                    'Vuex',                        'framework',  54),
('PyTorch',                 'PyTorch',                     'framework',  55),
('TensorFlow',              'TensorFlow',                  'framework',  56),
('Keras',                   'Keras',                       'framework',  57),
('scikit-learn',            'scikit-learn',                'framework',  58),
('LangChain',               'LangChain',                   'framework',  59),
('LlamaIndex',              'LlamaIndex',                  'framework',  60),
('Hugging Face Transformers','Hugging Face Transformers',  'framework',  61),
('OpenCV',                  'OpenCV',                      'framework',  62),
('Pandas',                  'Pandas',                      'framework',  63),
('NumPy',                   'NumPy',                       'framework',  64),
('Matplotlib',              'Matplotlib',                  'framework',  65),
('Apache Spark',            'Apache Spark',                'framework',  66),
('Apache Flink',            'Apache Flink',                'framework',  67),
('Hadoop',                  'Hadoop',                      'framework',  68),
('Kafka',                   'Apache Kafka',                'framework',  69),
('RabbitMQ',                'RabbitMQ',                    'framework',  70),
('Celery (Python)',         'Celery',                      'framework',  71),
('Flutter',                 'Flutter',                     'framework',  72),
('React Native',            'React Native',                'framework',  73),
('Expo',                    'Expo',                        'framework',  74),
('Ionic',                   'Ionic',                       'framework',  75),
('Electron',                'Electron',                    'framework',  76),
('Tauri',                   'Tauri',                       'framework',  77),
('Playwright',              'Playwright',                  'framework',  78),
('Cypress',                 'Cypress',                     'framework',  79),
('Jest',                    'Jest',                        'framework',  80),
('Vitest',                  'Vitest',                      'framework',  81),
('pytest',                  'pytest',                      'framework',  82),
('JUnit',                   'JUnit',                       'framework',  83),
('Storybook',               'Storybook',                   'framework',  84),
('Three.js',                'Three.js',                    'framework',  85),
('D3.js',                   'D3.js',                       'framework',  86),
('Socket.IO',               'Socket.IO',                   'framework',  87),
('WebRTC',                  'WebRTC',                      'framework',  88),
('Prisma',                  'Prisma ORM',                  'framework',  89),
('Drizzle ORM',             'Drizzle ORM',                 'framework',  90),

-- ══════════════════════════════════════════════════════════
-- CATEGORY: tool  (工具与平台)  ~80 entries
-- ══════════════════════════════════════════════════════════
('Git',                 'Git',                          'tool',   1),
('GitHub',              'GitHub',                       'tool',   2),
('GitLab',              'GitLab',                       'tool',   3),
('Bitbucket',           'Bitbucket',                    'tool',   4),
('Docker',              'Docker',                       'tool',   5),
('Kubernetes',          'Kubernetes (K8s)',              'tool',   6),
('Helm',                'Helm',                         'tool',   7),
('Terraform',           'Terraform',                    'tool',   8),
('Ansible',             'Ansible',                      'tool',   9),
('AWS',                 'Amazon Web Services (AWS)',     'tool',  10),
('Google Cloud',        'Google Cloud Platform (GCP)',  'tool',  11),
('Azure',               'Microsoft Azure',              'tool',  12),
('Vercel',              'Vercel',                       'tool',  13),
('Netlify',             'Netlify',                      'tool',  14),
('Heroku',              'Heroku',                       'tool',  15),
('Supabase',            'Supabase',                     'tool',  16),
('Firebase',            'Firebase',                     'tool',  17),
('PostgreSQL',          'PostgreSQL',                   'tool',  18),
('MySQL',               'MySQL',                        'tool',  19),
('MongoDB',             'MongoDB',                      'tool',  20),
('Redis',               'Redis',                        'tool',  21),
('Elasticsearch',       'Elasticsearch',                'tool',  22),
('ClickHouse',          'ClickHouse',                   'tool',  23),
('Snowflake',           'Snowflake',                    'tool',  24),
('BigQuery',            'Google BigQuery',              'tool',  25),
('dbt',                 'dbt (data build tool)',        'tool',  26),
('Airflow',             'Apache Airflow',               'tool',  27),
('Databricks',          'Databricks',                   'tool',  28),
('Tableau',             'Tableau',                      'tool',  29),
('Power BI',            'Microsoft Power BI',           'tool',  30),
('Grafana',             'Grafana',                      'tool',  31),
('Prometheus',          'Prometheus',                   'tool',  32),
('Datadog',             'Datadog',                      'tool',  33),
('Sentry',              'Sentry',                       'tool',  34),
('New Relic',           'New Relic',                    'tool',  35),
('Jenkins',             'Jenkins',                      'tool',  36),
('GitHub Actions',      'GitHub Actions',               'tool',  37),
('CircleCI',            'CircleCI',                     'tool',  38),
('ArgoCD',              'ArgoCD',                       'tool',  39),
('Nginx',               'Nginx',                        'tool',  40),
('Linux',               'Linux',                        'tool',  41),
('macOS',               'macOS',                        'tool',  42),
('VSCode',              'Visual Studio Code',           'tool',  43),
('IntelliJ IDEA',       'IntelliJ IDEA',                'tool',  44),
('Xcode',               'Xcode',                        'tool',  45),
('Android Studio',      'Android Studio',               'tool',  46),
('Postman',             'Postman',                      'tool',  47),
('Insomnia',            'Insomnia',                     'tool',  48),
('Figma',               'Figma',                        'tool',  49),
('Sketch',              'Sketch',                       'tool',  50),
('Adobe XD',            'Adobe XD',                     'tool',  51),
('Jira',                'Jira',                         'tool',  52),
('Confluence',          'Confluence',                   'tool',  53),
('Linear',              'Linear',                       'tool',  54),
('Notion',              'Notion',                       'tool',  55),
('Slack',               'Slack',                        'tool',  56),
('Salesforce',          'Salesforce CRM',               'tool',  57),
('HubSpot',             'HubSpot',                      'tool',  58),
('Stripe',              'Stripe',                       'tool',  59),
('Twilio',              'Twilio',                       'tool',  60),
('SendGrid',            'SendGrid',                     'tool',  61),
('Segment',             'Segment',                      'tool',  62),
('Mixpanel',            'Mixpanel',                     'tool',  63),
('Amplitude',           'Amplitude',                    'tool',  64),
('Google Analytics',    'Google Analytics',             'tool',  65),
('OpenAI API',          'OpenAI API',                   'tool',  66),
('Claude API',          'Anthropic Claude API',         'tool',  67),
('Langfuse',            'Langfuse',                     'tool',  68),
('Weights & Biases',    'Weights & Biases (W&B)',       'tool',  69),
('DVC',                 'DVC (Data Version Control)',   'tool',  70),
('Hadoop HDFS',         'Hadoop HDFS',                  'tool',  71),
('MinIO',               'MinIO',                        'tool',  72),
('Vault (HashiCorp)',    'HashiCorp Vault',              'tool',  73),
('Consul',              'HashiCorp Consul',             'tool',  74),
('Istio',               'Istio',                        'tool',  75),
('Linkerd',             'Linkerd',                      'tool',  76),
('Pulumi',              'Pulumi',                       'tool',  77),
('Cloudflare',          'Cloudflare',                   'tool',  78),
('CDN',                 'CDN (Content Delivery Network)','tool', 79),
('微信小程序',          'WeChat Mini Program',          'tool',  80),

-- ══════════════════════════════════════════════════════════
-- CATEGORY: soft_skill  (软技能)  ~50 entries
-- ══════════════════════════════════════════════════════════
('领导力',        'Leadership',                       'soft_skill',   1),
('团队协作',      'Teamwork & Collaboration',         'soft_skill',   2),
('项目管理',      'Project Management',               'soft_skill',   3),
('时间管理',      'Time Management',                  'soft_skill',   4),
('沟通能力',      'Communication Skills',             'soft_skill',   5),
('批判性思维',    'Critical Thinking',                'soft_skill',   6),
('问题解决',      'Problem Solving',                  'soft_skill',   7),
('创新思维',      'Innovation & Creative Thinking',   'soft_skill',   8),
('数据驱动决策',  'Data-Driven Decision Making',      'soft_skill',   9),
('跨文化沟通',    'Cross-Cultural Communication',     'soft_skill',  10),
('演讲与表达',    'Public Speaking & Presentation',   'soft_skill',  11),
('谈判技巧',      'Negotiation',                      'soft_skill',  12),
('客户关系管理',  'Client Relationship Management',   'soft_skill',  13),
('适应变化',      'Adaptability & Change Management', 'soft_skill',  14),
('自我驱动',      'Self-Motivated & Results-Oriented','soft_skill',  15),
('情商',          'Emotional Intelligence (EQ)',      'soft_skill',  16),
('冲突解决',      'Conflict Resolution',              'soft_skill',  17),
('教练与辅导',    'Coaching & Mentoring',             'soft_skill',  18),
('战略思维',      'Strategic Thinking',               'soft_skill',  19),
('产品思维',      'Product Thinking',                 'soft_skill',  20),
('用户同理心',    'User Empathy & UX Thinking',       'soft_skill',  21),
('迭代学习',      'Growth Mindset & Continuous Learning','soft_skill',22),
('目标管理 (OKR)','OKR Goal Setting',                 'soft_skill',  23),
('敏捷 / Scrum',  'Agile / Scrum Methodology',        'soft_skill',  24),
('跨部门协作',    'Cross-Functional Collaboration',   'soft_skill',  25),
('书面表达',      'Written Communication',            'soft_skill',  26),
('风险意识',      'Risk Awareness',                   'soft_skill',  27),
('压力管理',      'Stress Management',                'soft_skill',  28),
('复盘与反思',    'After-Action Review & Retrospective','soft_skill', 29),
('结构化思维',    'Structured Thinking',              'soft_skill',  30),
('快速学习',      'Fast Learning',                    'soft_skill',  31),
('商业敏感度',    'Business Acumen',                  'soft_skill',  32),
('注重细节',      'Attention to Detail',              'soft_skill',  33),
('多任务处理',    'Multitasking',                     'soft_skill',  34),
('诚信',          'Integrity & Professionalism',      'soft_skill',  35),
('远程协作',      'Remote Collaboration',             'soft_skill',  36),
('设计思维',      'Design Thinking',                  'soft_skill',  37),
('决策能力',      'Decision Making',                  'soft_skill',  38),
('预算管理',      'Budget Management',                'soft_skill',  39),
('变革管理',      'Change Management',                'soft_skill',  40),
('影响力',        'Influence Without Authority',      'soft_skill',  41),
('全球视野',      'Global Mindset',                   'soft_skill',  42),
('客户导向',      'Customer-Centric Mindset',         'soft_skill',  43),
('系统性思维',    'Systems Thinking',                 'soft_skill',  44),
('反馈文化',      'Feedback Culture',                 'soft_skill',  45),
('知识迁移',      'Knowledge Transfer',               'soft_skill',  46),
('抗压能力',      'Resilience Under Pressure',        'soft_skill',  47),
('职场政治敏感度','Organizational Savviness',         'soft_skill',  48),
('文档撰写',      'Technical Writing',                'soft_skill',  49),
('流程优化',      'Process Improvement',              'soft_skill',  50),

-- ══════════════════════════════════════════════════════════
-- CATEGORY: language  (语言证书)  ~35 entries
-- ══════════════════════════════════════════════════════════
('英语 (母语)',        'English (Native)',              'language',   1),
('英语 (流利)',        'English (Fluent)',              'language',   2),
('英语 (工作级)',      'English (Professional)',        'language',   3),
('英语 (基础)',        'English (Basic)',               'language',   4),
('普通话 (母语)',      'Mandarin Chinese (Native)',     'language',   5),
('普通话 (流利)',      'Mandarin Chinese (Fluent)',     'language',   6),
('粤语 (母语)',        'Cantonese (Native)',            'language',   7),
('粤语 (流利)',        'Cantonese (Fluent)',            'language',   8),
('日语 (JLPT N1)',     'Japanese (JLPT N1)',            'language',   9),
('日语 (JLPT N2)',     'Japanese (JLPT N2)',            'language',  10),
('日语 (JLPT N3)',     'Japanese (JLPT N3)',            'language',  11),
('韩语 (TOPIK 6级)',   'Korean (TOPIK Level 6)',        'language',  12),
('韩语 (TOPIK 5级)',   'Korean (TOPIK Level 5)',        'language',  13),
('德语 (C1)',          'German (C1)',                   'language',  14),
('德语 (B2)',          'German (B2)',                   'language',  15),
('法语 (C1)',          'French (C1)',                   'language',  16),
('法语 (B2)',          'French (B2)',                   'language',  17),
('西班牙语 (B2)',      'Spanish (B2)',                  'language',  18),
('葡萄牙语 (B2)',      'Portuguese (B2)',               'language',  19),
('俄语 (B2)',          'Russian (B2)',                  'language',  20),
('阿拉伯语 (B2)',      'Arabic (B2)',                   'language',  21),
('印地语 (流利)',      'Hindi (Fluent)',                'language',  22),
('泰语 (基础)',        'Thai (Basic)',                  'language',  23),
('越南语 (基础)',      'Vietnamese (Basic)',            'language',  24),
('意大利语 (B2)',      'Italian (B2)',                  'language',  25),
('CET-4',             'CET-4 (College English Test 4)', 'language', 26),
('CET-6',             'CET-6 (College English Test 6)', 'language', 27),
('雅思 7.0+',         'IELTS 7.0+',                    'language',  28),
('雅思 6.5',          'IELTS 6.5',                     'language',  29),
('托福 100+',         'TOEFL 100+',                    'language',  30),
('托福 90+',          'TOEFL 90+',                     'language',  31),
('GRE',               'GRE',                           'language',  32),
('GMAT',              'GMAT',                          'language',  33),
('HSK 6级',           'HSK Level 6',                   'language',  34),
('普通话水平测试 一级','Putonghua Proficiency Test Level 1','language',35)

ON CONFLICT (name_zh) DO NOTHING;

-- Verify minimum count (reference only):
-- SELECT category, count(*) FROM seed_skills GROUP BY category ORDER BY category;
-- Expected totals: programming≥50, framework≥90, tool≥80, soft_skill≥50, language≥35  → total ≥ 305
